
# Task name - used to pick the class to load
task_name: IDPMinEffort
# experiment name. defaults to name of training config
experiment: 'IDP'
experiment_name: ''

# if set to positive integer, overrides the default number of environments

# hyper-parameter tuning
num_envs: ''
gamma: ''
tau: ''
kl_threshold: ''
horizon_length: ''
minibatch_size: ''
mini_epochs: ''
exp_time: ''
entropy_coef: ''
fixed_sigma: ''
lr_schedule: ''
lr: ''
# learning parameter study
lim_level: 0.5
tqrate_ratio: 0.0
tqcost_ratio: 1.0
stcost_ratio: 1.0
const_ratio: 1.0
ank_ratio: ''
vel_ratio: ''
tq_ratio: ''
ankle_limit: 'soft'
stptb: ''
edptb: ''
ptb_act_time: 0.275
ptb_type: '5th'
delay_randomize: 0.0
delay: True
delayed_time: 0.1
tqr_regularize_type: 'torque_rate'
action_as_state: False
use_curriculum: ''
cost_type: ''
tqr_limit: 1
# curriculum parameter
min_tqr_limit: ''
min_avg_coeff: ''
max_lean_angle: ''
max_edptb: ''
end_epoch: ''

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'cpu'
# device for running physics simulation
sim_device: 'cpu'
# device to run RL
rl_device: 'cpu'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: True
load_checkpoint: False
# used to set checkpoint path
checkpoint: 'runs/example_result/nn/IDP.pth'
const_type: 'ankle_torque'
stiff_ank: 250
ankle_torque_max: 100
clipActions: 1.0
avg_coeff: 1.0
upright_type: 0.0
save_mat: False
save_fig: False
show_fig: True
fig_path: ''
mat_path: ''
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False
full_experiment_name: None

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
wandb_tags: []
wandb_logcode_dir: ''

capture_video: False
capture_video_freq: 3200
capture_video_len: 600
force_render: False

# disables rendering
headless: True

# set default task and default training config based on task
defaults:
  - task: IDP
  - train: ${task}PPO
  - pbt: no_pbt
  - override hydra/job_logging: disabled
  - _self_

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .
