
# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: 'IDP'
experiment_name: '.'

# if set to positive integer, overrides the default number of environments

# hyper-parameter tuning
num_envs: ''
gamma: ''
tau: ''
kl_threshold: ''
horizon_length: ''
minibatch_size: ''
exp_time: ''
# learning parameter study
lim_level: ''
tqrate_ratio: ''
tqcost_ratio: ''
stcost_ratio: ''

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'cpu'
# device for running physics simulation
sim_device: 'cpu'
# device to run RL
rl_device: 'cpu'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: True
load_checkpoint: False
# used to set checkpoint path
checkpoint: 'runs/paramTuning/exp5/numEnvs2048gamma0.999tau0.98/limLevel0/atm100_as100/IDP_2024-12-10_10-03-54/nn/IDP.pth'
stiff_ank: 100
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False
full_experiment_name: None

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
wandb_tags: []
wandb_logcode_dir: '' 

capture_video: False
capture_video_freq: 3200
capture_video_len: 600
force_render: False

# disables rendering
headless: True

# set default task and default training config based on task
defaults:
  - task: IDP
  - train: ${task}PPO
  - pbt: no_pbt
  - override hydra/job_logging: disabled
  - _self_

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .

